### ISSUE TITLE
Sidebar overlay on footer !

### ISSUE THREAD

**Issue by icoderharshit** [sButtons/sbuttons#695] opened 2020-10-06 10:32 UTC
**1 - Describe the bug**
Sidebar overlaying on footer when last item (Windows 95) is in active state i.e clicked

**2 - Expected behavior of what should have happened (if applicable)**
This should not overlay over the footer, and the footer must be shifted downwards for a better user experience.

**3 - Screenshots (if applicable)**
![bug](https://user-images.githubusercontent.com/55023091/95190659-4d45dd80-07ed-11eb-88fc-dc3d26d8af73.PNG)

**4 - Additional notes**
Although, I found this bug out but due to some other work; can't work over this straight away..So, I would like to recommend a friend of mine for this task; She'll might help!
@ibhavikamalhotra or https://github.com/ibhavikamalhotra
Kindly assign this task to her @shahednasser and see to it :)

**Comment by shahednasser** [comment] 2020-10-06 10:59
Hello @icoderharshit this issue is a duplicate of #564 and someone is working on it. Thank you!

**Closed by shahednasser** 2020-10-06 10:59 UTC
Labels: bug
