### ISSUE TITLE
Toggle Button as a radio button dosent get untoggled in documentation.html file

### ISSUE THREAD

**Issue by alok1929** [sButtons/sbuttons#1196] opened 2020-12-10 10:23 UTC
toggle button gets toggled but cant untoggle it

**Comment by shahednasser** [comment] 2020-12-10 12:48
Thank you for reporting this! Let me know if you'd like to work on it.

**Comment by Arnab-Bhakta** [comment] 2020-12-11 03:22
Looks like it's an expected behavior. Radio buttons cannot be untoggled on its own. If you select/toggle other option, then previous one will be unselected/untoggled.

So, the example can be modified like this.
`<input type="radio" class="sbtn toggle-btn" name="selectOption">
    <label>Option1</label>
    <br>
    <input type="radio" class="sbtn toggle-btn" name="selectOption">
    <label>Option2</label>
    <br>
    <input type="radio" class="sbtn toggle-btn" name="selectOption">
    <label>Option3</label>
    <br>`

I would like to make a pr on this.

**Comment by shahednasser** [comment] 2020-12-11 11:11
Good idea @Arnab-Bhakta . I see you made the changes but still haven't created the PR. Once you're ready please create it and please check out the [contributing guidelines](https://github.com/sButtons/sbuttons/blob/8e8568e858a830a3182102a956ebdbe08284a430/CONTRIBUTING.md). If you need any help let me know.

**Comment by harshitaaaaaa** [comment] 2020-12-17 09:09
Hey, I want to work on this issue but coudn't find out where to make changes. Do we have to do it in toggle.less? Please guide me with that.

**Comment by shahednasser** [comment] 2020-12-17 19:09
Hello @harshitaaaaaa unfortunately someone else was assigned to this issue and has resolved it

**Closed** 2020-12-17 19:09 UTC
Labels: Priority: Medium, bug, documentation, good first issue, help wanted, up-for-grabs, website
