### ISSUE TITLE
changes on get updated on website.

### ISSUE THREAD

**Issue by mayankmohak** [sButtons/sbuttons#1513] opened 2021-10-05 18:03 UTC
**1 - Describe the bug**
Changes are not being updated on the website.
Because `dist/sbuttons.min.css` file is not being updated

**2 - Expected behavior of what should have happened (if applicable)**
compiled file make changes in the `sbuttons.min` file so to make changes properly it should also change file `sbuttons.min.css`

**3 - Screenshots (if applicable)**
NA

**4 - Additional notes**
I was trying to add a new button in existing type and it is compiled correctly to `sbuttons.css` file but it is not updating `sbuttons.min.css` file.

**Comment by shahednasser** [comment] 2021-10-05 19:11
Hi @mayankmohak this is actually not a bug. This is because in the contributing guidelines it states that you only need to run `npm run compile`. However, after changing the website and using `sbuttons.min.css` from the repository, you also need to run `npm run clean-css`.

I think we should change the issue to fix the contributing guidelines instead to add a note about this. I'll close this issue and add a new issue about this. Thank you for reporting this!

**Closed by shahednasser** 2021-10-05 19:11 UTC
Labels: bug
